import { useEffect, useMemo, useState } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import { ArrowRight, BarChart3, CalendarClock, CheckCircle2, Clock3, ExternalLink, FileText, LayoutDashboard, Package, Plus, Settings, ShieldCheck, ShoppingBag, Trash2, Video } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { ShopeePublisherComposer } from "@/features/publisher/components/ShopeePublisherComposer";
import { deleteShopeeDraft, formatShopeeDate, loadShopeeDrafts, type ShopeeDraft } from "@/features/shopee/shopee-store";

const tabs = [
  { to: "/shopee", label: "Overview", icon: LayoutDashboard, end: true },
  { to: "/shopee/videos/new", label: "Create Video", icon: Plus },
  { to: "/shopee/videos", label: "Videos", icon: Video },
  { to: "/shopee/products", label: "Products", icon: Package },
  { to: "/shopee/drafts", label: "Drafts", icon: FileText },
  { to: "/shopee/scheduled", label: "Scheduled", icon: CalendarClock },
  { to: "/shopee/analytics", label: "Analytics", icon: BarChart3 },
  { to: "/shopee/settings", label: "Settings", icon: Settings },
];

export function ShopeeWorkspacePage() {
  const location = useLocation();
  const [drafts, setDrafts] = useState<ShopeeDraft[]>(() => loadShopeeDrafts());
  useEffect(() => {
    const sync = () => setDrafts(loadShopeeDrafts());
    window.addEventListener("nexapa:shopee-drafts", sync);
    window.addEventListener("storage", sync);
    sync();
    return () => { window.removeEventListener("nexapa:shopee-drafts", sync); window.removeEventListener("storage", sync); };
  }, [location.pathname]);

  const title = location.pathname === "/shopee/videos/new" ? "Create Shopee Video" : location.pathname === "/shopee/products" ? "Affiliate Products" : location.pathname === "/shopee/drafts" ? "Shopee Drafts" : location.pathname === "/shopee/scheduled" ? "Scheduled Videos" : location.pathname === "/shopee/analytics" ? "Shopee Analytics" : location.pathname === "/shopee/settings" ? "Shopee Settings" : location.pathname === "/shopee/videos" ? "Shopee Videos" : "Shopee Workspace";

  return <div className="min-w-0 bg-transparent"><PageHeader eyebrow="COMMERCE / SHOPEE" title={title} description="Affiliate video workflow prepared for Shopee Sandbox and Production APIs." actions={<Link to="/shopee/videos/new" className="inline-flex h-9 items-center gap-2 rounded-xl bg-orange-500 px-4 text-[12px] font-semibold text-white shadow-sm hover:bg-orange-600"><Plus className="h-4 w-4"/> New Video</Link>}/><div className="mx-auto max-w-[1440px] px-4 py-6 sm:px-6 lg:px-8"><nav className="mb-5 flex gap-2 overflow-x-auto rounded-2xl border border-white/20 bg-white/10 p-2 backdrop-blur-xl" aria-label="Shopee workspace">{tabs.map(({to,label,icon:Icon,end}) => <NavLink key={to} to={to} end={end} className={({isActive}) => `inline-flex h-9 shrink-0 items-center gap-2 rounded-xl px-3 text-[11px] font-medium transition ${isActive ? "bg-orange-500 text-white shadow-sm" : "text-slate-600 hover:bg-white/20 hover:text-slate-900"}`}><Icon className="h-4 w-4"/>{label}</NavLink>)}</nav><ShopeeView path={location.pathname} drafts={drafts} onDelete={(id) => setDrafts(deleteShopeeDraft(id))}/></div></div>;
}

function ShopeeView({path,drafts,onDelete}:{path:string;drafts:ShopeeDraft[];onDelete:(id:string)=>void}) {
  if (path === "/shopee/videos/new") return <ShopeePublisherComposer />;
  if (path === "/shopee/products") return <ProductsView drafts={drafts}/>;
  if (path === "/shopee/drafts") return <DraftList drafts={drafts.filter((item) => item.status !== "scheduled")} empty="No Shopee drafts yet." onDelete={onDelete}/>;
  if (path === "/shopee/scheduled") return <DraftList drafts={drafts.filter((item) => item.status === "scheduled")} empty="No scheduled Shopee videos." onDelete={onDelete}/>;
  if (path === "/shopee/videos") return <DraftList drafts={drafts} empty="No prepared Shopee videos yet." onDelete={onDelete}/>;
  if (path === "/shopee/analytics") return <AnalyticsView/>;
  if (path === "/shopee/settings") return <SettingsView/>;
  return <Overview drafts={drafts}/>;
}

function Overview({drafts}:{drafts:ShopeeDraft[]}) {
  const scheduled = drafts.filter((item) => item.status === "scheduled").length;
  const ready = drafts.filter((item) => item.status === "ready").length;
  const products = new Set(drafts.map((item) => item.productUrl).filter(Boolean)).size;
  return <div className="space-y-5"><div className="rounded-2xl border border-amber-400/25 bg-amber-400/10 p-5 backdrop-blur-xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><ShieldCheck className="h-6 w-6 text-amber-700"/><div><h2 className="text-[14px] font-semibold text-amber-950">Developer profile under review</h2><p className="mt-1 text-[11px] text-amber-900/75">Workspace and draft workflow are ready. Connect and publish unlock after Shopee enables Sandbox onboarding.</p></div></div><span className="w-fit rounded-full border border-amber-400/30 bg-white/20 px-3 py-1 text-[10px] font-semibold text-amber-900">APPROVAL PENDING</span></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{label:"Total drafts",value:drafts.length,icon:FileText},{label:"Ready",value:ready,icon:CheckCircle2},{label:"Scheduled",value:scheduled,icon:CalendarClock},{label:"Product links",value:products,icon:Package}].map(({label,value,icon:Icon}) => <div key={label} className="rounded-2xl border border-white/20 bg-white/10 p-5 shadow-card backdrop-blur-xl"><Icon className="h-5 w-5 text-orange-600"/><p className="mt-5 text-2xl font-semibold text-slate-950">{value}</p><p className="mt-1 text-[11px] text-slate-600">{label}</p></div>)}</div><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border border-white/20 bg-white/10 p-5 shadow-card backdrop-blur-xl"><div className="flex items-center justify-between"><h2 className="text-[13px] font-semibold text-slate-900">Recent drafts</h2><Link to="/shopee/drafts" className="text-[11px] font-medium text-orange-700">View all</Link></div><div className="mt-4">{drafts.length ? drafts.slice(0,4).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 border-t border-white/15 py-3 first:border-0"><div className="min-w-0"><p className="truncate text-[12px] font-medium text-slate-900">{item.title}</p><p className="mt-0.5 text-[10px] text-slate-500">Updated {formatShopeeDate(item.updatedAt)}</p></div><Link to={`/shopee/videos/new?draft=${item.id}`} className="text-[10px] font-semibold text-orange-700">Edit</Link></div>) : <Empty text="Create your first Shopee video draft."/>}</div></div><div className="rounded-2xl border border-white/20 bg-white/10 p-5 shadow-card backdrop-blur-xl"><ShoppingBag className="h-6 w-6 text-orange-600"/><h2 className="mt-4 text-[14px] font-semibold text-slate-900">Start preparing</h2><p className="mt-2 text-[11px] leading-5 text-slate-600">Add a video, caption, affiliate product URL, and optional schedule.</p><Link to="/shopee/videos/new" className="mt-5 inline-flex h-9 w-full items-center justify-center gap-2 rounded-xl bg-orange-500 text-[11px] font-semibold text-white">Create Video <ArrowRight className="h-4 w-4"/></Link></div></div></div>;
}

function DraftList({drafts,empty,onDelete}:{drafts:ShopeeDraft[];empty:string;onDelete:(id:string)=>void}) { return <div className="rounded-2xl border border-white/20 bg-white/10 p-5 shadow-card backdrop-blur-xl">{drafts.length ? <div className="space-y-3">{drafts.map((item) => <article key={item.id} className="flex flex-col gap-4 rounded-xl border border-white/20 bg-white/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-[13px] font-semibold text-slate-900">{item.title}</h3><span className="rounded-full border border-orange-300/30 bg-orange-400/10 px-2 py-0.5 text-[9px] font-semibold uppercase text-orange-800">{item.status}</span></div><p className="mt-1 line-clamp-1 text-[11px] text-slate-600">{item.caption || "No caption"}</p><div className="mt-2 flex flex-wrap gap-3 text-[10px] text-slate-500"><span>{item.videoName ?? "Video must be re-selected"}</span>{item.scheduleAt && <span><Clock3 className="mr-1 inline h-3 w-3"/>{formatShopeeDate(item.scheduleAt)}</span>}</div></div><div className="flex shrink-0 gap-2"><Link to={`/shopee/videos/new?draft=${item.id}`} className="inline-flex h-8 items-center rounded-lg border border-white/20 bg-white/15 px-3 text-[10px] font-semibold text-slate-700">Edit</Link><button type="button" onClick={() => { if (window.confirm(`Delete ${item.title}?`)) onDelete(item.id); }} className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-red-300/30 bg-red-400/10 text-red-700"><Trash2 className="h-4 w-4"/></button></div></article>)}</div> : <Empty text={empty}/>}</div>; }

function ProductsView({drafts}:{drafts:ShopeeDraft[]}) { const products = useMemo(() => Array.from(new Set(drafts.map((item) => item.productUrl).filter(Boolean))), [drafts]); return <div className="rounded-2xl border border-white/20 bg-white/10 p-5 shadow-card backdrop-blur-xl"><div className="flex items-center justify-between"><div><h2 className="text-[14px] font-semibold text-slate-900">Prepared product links</h2><p className="mt-1 text-[11px] text-slate-600">Local links collected from Shopee drafts.</p></div><span className="rounded-full bg-orange-500/10 px-3 py-1 text-[10px] font-semibold text-orange-800">{products.length} products</span></div>{products.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{products.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-white/20 bg-white/10 p-4 hover:bg-white/20"><Package className="h-5 w-5 shrink-0 text-orange-600"/><span className="min-w-0 flex-1 truncate text-[11px] text-slate-700">{url}</span><ExternalLink className="h-4 w-4 text-slate-400"/></a>)}</div> : <Empty text="Product search activates after Sandbox; product URLs added to drafts will appear here."/>}</div>; }

function AnalyticsView() { return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Views","Likes","Comments","Orders"].map((label) => <div key={label} className="rounded-2xl border border-white/20 bg-white/10 p-5 shadow-card backdrop-blur-xl"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-4 text-2xl font-semibold text-slate-400">—</p><p className="mt-1 text-[10px] text-slate-500">Available after API connection</p></div>)}</div><div className="rounded-2xl border border-white/20 bg-white/10 p-8 text-center shadow-card backdrop-blur-xl"><BarChart3 className="mx-auto h-8 w-8 text-orange-500"/><h2 className="mt-4 text-[14px] font-semibold text-slate-900">Analytics adapter ready for integration</h2><p className="mx-auto mt-2 max-w-xl text-[11px] leading-5 text-slate-600">This page will load video performance from Shopee after Sandbox validates the response format.</p></div></div>; }

function SettingsView() { return <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/20 bg-white/10 p-5 shadow-card backdrop-blur-xl"><h2 className="text-[14px] font-semibold text-slate-900">Connection status</h2><div className="mt-4 flex items-center justify-between rounded-xl border border-amber-300/30 bg-amber-400/10 p-4"><div><p className="text-[12px] font-semibold text-amber-950">Profile under review</p><p className="mt-1 text-[10px] text-amber-800">Sandbox credentials are not available yet.</p></div><ShieldCheck className="h-5 w-5 text-amber-700"/></div><button type="button" disabled className="mt-4 h-10 w-full cursor-not-allowed rounded-xl bg-slate-300/40 text-[11px] font-semibold text-slate-500">Connect Shopee Sandbox</button></div><div className="rounded-2xl border border-white/20 bg-white/10 p-5 shadow-card backdrop-blur-xl"><h2 className="text-[14px] font-semibold text-slate-900">Server callbacks</h2>{[["OAuth callback","https://api.nexapa.app/api/v1/oauth/shopee/callback"],["Webhook","https://api.nexapa.app/api/v1/webhooks/shopee"]].map(([label,value]) => <div key={label} className="mt-4"><p className="text-[10px] font-medium text-slate-600">{label}</p><code className="mt-1 block overflow-x-auto rounded-xl bg-slate-950/80 px-3 py-2 text-[10px] text-slate-100">{value}</code></div>)}<p className="mt-4 text-[10px] leading-4 text-slate-500">Partner Key must only be configured on the Nexapa API server.</p></div></div>; }

function Empty({text}:{text:string}) { return <div className="py-12 text-center"><ShoppingBag className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 text-[12px] text-slate-500">{text}</p></div>; }
